//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudiosSocioeconomicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuestas
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Encuestadores_Id { get; set; }
        public Nullable<System.DateTime> AsingEncuestor { get; set; }
        public Nullable<System.DateTime> CreateRow { get; set; }
        public Nullable<System.DateTime> ActiveCount { get; set; }
        public Nullable<System.DateTime> DesactiveCount { get; set; }
        public Nullable<System.DateTime> UpdateCount { get; set; }
    }
}
